/********************************************************************************************************
 * @file    tlka_hfp_plc_api.h
 *
 * @brief   This is the header file for TLSR/TL
 *
 * @author  Bluetooth Group
 * @date    2024
 *
 * @par     Copyright (c) 2024, Telink Semiconductor (Shanghai) Co., Ltd. ("TELINK")
 *
 *          Licensed under the Apache License, Version 2.0 (the "License");
 *          you may not use this file except in compliance with the License.
 *          You may obtain a copy of the License at
 *
 *              http://www.apache.org/licenses/LICENSE-2.0
 *
 *          Unless required by applicable law or agreed to in writing, software
 *          distributed under the License is distributed on an "AS IS" BASIS,
 *          WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *          See the License for the specific language governing permissions and
 *          limitations under the License.
 *
 *******************************************************************************************************/
#ifndef TLKA_HFP_PLC_API_H
#define TLKA_HFP_PLC_API_H

/*! Construct version number from major/minor/micro values. */
#define PLC_HF_VERSION_INT(major, minor, micro) (((major) << 16) | ((minor) << 8) | (micro))

/*! Version number to ensure header and binary are matching. */
#define PLC_HF_VERSION PLC_HF_VERSION_INT(1, 2, 6)

typedef enum
{
    PLCHFP_OK         = 0,
    PLCHFP_ERROR_INIT = 1,
    PLCHFP_ERROR_INVALID_FRAMESIZE,
} PLCHFP_Error;

#define SBCRT           (72)      /* SBC Reconvergence Time (samples) */
#define OLAL            (32)      /* OverLap-Add Length (samples) */

#define FRAMESIZE_MAX   (240)     /* max framesize */
#define SEARCH_LEN_MAX  (256 * 3) /* 16ms for 48khz */
#define PATTERN_LEN_MAX (64 * 3)  /* 4ms for 48khz*/
#define LHIST_MAX       (SEARCH_LEN_MAX + FRAMESIZE_MAX - 1)

/* PLC State Information */
typedef struct _plc_state
{
    float hist[LHIST_MAX + FRAMESIZE_MAX + SBCRT + OLAL];
    short bestlag;
    int   nbf;
    float g;
    float attenincr;
    int   faster_en;

    int ndec;
    int frame_size;
    int samplerate;
    int pattern_len;
    int search_len;
    int lhist;
} plc_state_t;

typedef struct
{
    int samplerate;
    int frame_size;
} HFP_PLC_CFG_PARAM;

/*! Return library version number. It should match PLC_HF_VERSION. */
int tlka_hfp_plc_get_version(void);

/*! Get the memory size needed by the PLC module
 *
 *  \return                 Size in bytes.
 */
int tlka_hfp_plc_get_size();

/*!
 *  Initialize PLC module.
 *
 *  This function is used to fill a user-allocated plc struct.
 *
 *  \param[o]   plc_state   Pointer to allocated PLC memory. It must have a size provided
 *                          by plc_hfp_get_size()
 *  \param[i]   samplerate  Input sampling rate.
 *  \param[i]   frame_size  Input frame size, should be no more than FRAMESIZE_MAX.
 *  \return                 PLCHFP_OK on success or appropriate error code.
 */
PLCHFP_Error tlka_hfp_plc_init(plc_state_t *plc_state, HFP_PLC_CFG_PARAM plc_param);

/*!
 *  Call this function while a packet loss happened.
 *
 *  \param[o]   plc_state   Pointer to allocated PLC memory. It must have a size provided
 *                          by plc_hfp_get_size()
 *  \param[i]   ZIRbuf      The output data generated by  decoder while pushing a zero
 *                          frame into  decoder.
 *  \param[o]   out         PLC output.
 *
 *  \return                 PLCHFP_OK on success or appropriate error code.
 */
PLCHFP_Error tlka_hfp_plc_bad_frame(plc_state_t *plc_state, short *ZIRbuf, short *out);

/*!
 *  Call this function while processing a good frame.
 *
 *  \param[o]   plc_state   Pointer to allocated PLC memory. It must have a size provided
 *                          by plc_hfp_get_size()
 *  \param[i]   in          The pcm data generated by sbc decoder
 *                          frame into  decoder.
 *  \param[o]   out         PLC output.
 *
 *  \return                 PLCHFP_OK on success or appropriate error code.
 */
PLCHFP_Error tlka_hfp_plc_good_frame(plc_state_t *plc_state, short *in, short *out);

#endif /*  TLKA_HFP_PLC_API_H */
