/********************************************************************************************************
 * @file    cap_uc.h
 *
 * @brief   This is the header file for TLSR/TL
 *
 * @author  Bluetooth Group
 * @date    2024
 *
 * @par     Copyright (c) 2024, Telink Semiconductor (Shanghai) Co., Ltd.
 *          All rights reserved.
 *
 *          The information contained herein is confidential property of Telink
 *          Semiconductor (Shanghai) Co., Ltd. and is available under the terms
 *          of Commercial License Agreement between Telink Semiconductor (Shanghai)
 *          Co., Ltd. and the licensee or the terms described here-in. This heading
 *          MUST NOT be removed from this file.
 *
 *          Licensee shall not delete, modify or alter (or permit any third party to delete, modify, or
 *          alter) any information contained herein in whole or in part except as expressly authorized
 *          by Telink semiconductor (shanghai) Co., Ltd. Otherwise, licensee shall be solely responsible
 *          for any claim to the extent arising out of or relating to such deletion(s), modification(s)
 *          or alteration(s).
 *
 *          Licensees are granted free, non-transferable use of the information in this
 *          file under Mutual Non-Disclosure Agreement. NO WARRANTY of ANY KIND is provided.
 *
 *******************************************************************************************************/

#define LEA_CAPUC_LC3_8_1_LEFT_LOW_LATENCY         LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_8_1, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_8_1_RIGHT_LOW_LATENCY        LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_8_1, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_8_1_STEREO_LOW_LATENCY       LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_8_1, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_8_1_LEFT_BALANCED            LEA_ASE_CODEC_CONFIG_BALANCED(LC3_8_1, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_8_1_RIGHT_BALANCED           LEA_ASE_CODEC_CONFIG_BALANCED(LC3_8_1, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_8_1_STEREO_BALANCED          LEA_ASE_CODEC_CONFIG_BALANCED(LC3_8_1, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_8_1_LEFT_HIGH_RELIABILITY    LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_8_1, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_8_1_RIGHT_HIGH_RELIABILITY   LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_8_1, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_8_1_STEREO_HIGH_RELIABILITY  LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_8_1, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_8_2_LEFT_LOW_LATENCY         LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_8_2, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_8_2_RIGHT_LOW_LATENCY        LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_8_2, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_8_2_STEREO_LOW_LATENCY       LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_8_2, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_8_2_LEFT_BALANCED            LEA_ASE_CODEC_CONFIG_BALANCED(LC3_8_2, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_8_2_RIGHT_BALANCED           LEA_ASE_CODEC_CONFIG_BALANCED(LC3_8_2, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_8_2_STEREO_BALANCED          LEA_ASE_CODEC_CONFIG_BALANCED(LC3_8_2, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_8_2_LEFT_HIGH_RELIABILITY    LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_8_2, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_8_2_RIGHT_HIGH_RELIABILITY   LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_8_2, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_8_2_STEREO_HIGH_RELIABILITY  LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_8_2, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)

#define LEA_CAPUC_LC3_16_1_LEFT_LOW_LATENCY        LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_16_1, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_16_1_RIGHT_LOW_LATENCY       LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_16_1, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_16_1_STEREO_LOW_LATENCY      LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_16_1, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_16_1_LEFT_BALANCED           LEA_ASE_CODEC_CONFIG_BALANCED(LC3_16_1, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_16_1_RIGHT_BALANCED          LEA_ASE_CODEC_CONFIG_BALANCED(LC3_16_1, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_16_1_STEREO_BALANCED         LEA_ASE_CODEC_CONFIG_BALANCED(LC3_16_1, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_16_1_LEFT_HIGH_RELIABILITY   LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_16_1, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_16_1_RIGHT_HIGH_RELIABILITY  LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_16_1, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_16_1_STEREO_HIGH_RELIABILITY LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_16_1, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_16_2_LEFT_LOW_LATENCY        LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_16_2, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_16_2_RIGHT_LOW_LATENCY       LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_16_2, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_16_2_STEREO_LOW_LATENCY      LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_16_2, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_16_2_LEFT_BALANCED           LEA_ASE_CODEC_CONFIG_BALANCED(LC3_16_2, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_16_2_RIGHT_BALANCED          LEA_ASE_CODEC_CONFIG_BALANCED(LC3_16_2, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_16_2_STEREO_BALANCED         LEA_ASE_CODEC_CONFIG_BALANCED(LC3_16_2, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_16_2_LEFT_HIGH_RELIABILITY   LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_16_2, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_16_2_RIGHT_HIGH_RELIABILITY  LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_16_2, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_16_2_STEREO_HIGH_RELIABILITY LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_16_2, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)

#define LEA_CAPUC_LC3_24_1_LEFT_LOW_LATENCY        LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_24_1, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_24_1_RIGHT_LOW_LATENCY       LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_24_1, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_24_1_STEREO_LOW_LATENCY      LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_24_1, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_24_1_LEFT_BALANCED           LEA_ASE_CODEC_CONFIG_BALANCED(LC3_24_1, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_24_1_RIGHT_BALANCED          LEA_ASE_CODEC_CONFIG_BALANCED(LC3_24_1, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_24_1_STEREO_BALANCED         LEA_ASE_CODEC_CONFIG_BALANCED(LC3_24_1, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_24_1_LEFT_HIGH_RELIABILITY   LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_24_1, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_24_1_RIGHT_HIGH_RELIABILITY  LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_24_1, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_24_1_STEREO_HIGH_RELIABILITY LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_24_1, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_24_2_LEFT_LOW_LATENCY        LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_24_2, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_24_2_RIGHT_LOW_LATENCY       LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_24_2, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_24_2_STEREO_LOW_LATENCY      LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_24_2, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_24_2_LEFT_BALANCED           LEA_ASE_CODEC_CONFIG_BALANCED(LC3_24_2, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_24_2_RIGHT_BALANCED          LEA_ASE_CODEC_CONFIG_BALANCED(LC3_24_2, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_24_2_STEREO_BALANCED         LEA_ASE_CODEC_CONFIG_BALANCED(LC3_24_2, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_24_2_LEFT_HIGH_RELIABILITY   LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_24_2, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_24_2_RIGHT_HIGH_RELIABILITY  LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_24_2, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_24_2_STEREO_HIGH_RELIABILITY LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_24_2, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)

#define LEA_CAPUC_LC3_32_1_LEFT_LOW_LATENCY        LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_32_1, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_32_1_RIGHT_LOW_LATENCY       LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_32_1, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_32_1_STEREO_LOW_LATENCY      LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_32_1, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_32_1_LEFT_BALANCED           LEA_ASE_CODEC_CONFIG_BALANCED(LC3_32_1, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_32_1_RIGHT_BALANCED          LEA_ASE_CODEC_CONFIG_BALANCED(LC3_32_1, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_32_1_STEREO_BALANCED         LEA_ASE_CODEC_CONFIG_BALANCED(LC3_32_1, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_32_1_LEFT_HIGH_RELIABILITY   LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_32_1, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_32_1_RIGHT_HIGH_RELIABILITY  LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_32_1, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_32_1_STEREO_HIGH_RELIABILITY LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_32_1, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_32_2_LEFT_LOW_LATENCY        LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_32_2, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_32_2_RIGHT_LOW_LATENCY       LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_32_2, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_32_2_STEREO_LOW_LATENCY      LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_32_2, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_32_2_LEFT_BALANCED           LEA_ASE_CODEC_CONFIG_BALANCED(LC3_32_2, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_32_2_RIGHT_BALANCED          LEA_ASE_CODEC_CONFIG_BALANCED(LC3_32_2, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_32_2_STEREO_BALANCED         LEA_ASE_CODEC_CONFIG_BALANCED(LC3_32_2, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_32_2_LEFT_HIGH_RELIABILITY   LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_32_2, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_32_2_RIGHT_HIGH_RELIABILITY  LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_32_2, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_32_2_STEREO_HIGH_RELIABILITY LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_32_2, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)

#define LEA_CAPUC_LC3_48_1_LEFT_LOW_LATENCY        LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_1, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_1_RIGHT_LOW_LATENCY       LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_1, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_1_STEREO_LOW_LATENCY      LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_1, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_1_LEFT_BALANCED           LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_1, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_1_RIGHT_BALANCED          LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_1, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_1_STEREO_BALANCED         LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_1, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_1_LEFT_HIGH_RELIABILITY   LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_1, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_1_RIGHT_HIGH_RELIABILITY  LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_1, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_1_STEREO_HIGH_RELIABILITY LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_1, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_2_LEFT_LOW_LATENCY        LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_2, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_2_RIGHT_LOW_LATENCY       LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_2, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_2_STEREO_LOW_LATENCY      LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_2, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_2_LEFT_BALANCED           LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_2, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_2_RIGHT_BALANCED          LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_2, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_2_STEREO_BALANCED         LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_2, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_2_LEFT_HIGH_RELIABILITY   LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_2, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_2_RIGHT_HIGH_RELIABILITY  LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_2, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_2_STEREO_HIGH_RELIABILITY LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_2, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_3_LEFT_LOW_LATENCY        LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_3, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_3_RIGHT_LOW_LATENCY       LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_3, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_3_STEREO_LOW_LATENCY      LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_3, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_3_LEFT_BALANCED           LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_3, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_3_RIGHT_BALANCED          LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_3, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_3_STEREO_BALANCED         LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_3, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_3_LEFT_HIGH_RELIABILITY   LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_3, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_3_RIGHT_HIGH_RELIABILITY  LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_3, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_3_STEREO_HIGH_RELIABILITY LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_3, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_4_LEFT_LOW_LATENCY        LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_4, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_4_RIGHT_LOW_LATENCY       LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_4, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_4_STEREO_LOW_LATENCY      LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_4, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_4_LEFT_BALANCED           LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_4, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_4_RIGHT_BALANCED          LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_4, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_4_STEREO_BALANCED         LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_4, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_4_LEFT_HIGH_RELIABILITY   LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_4, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_4_RIGHT_HIGH_RELIABILITY  LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_4, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_4_STEREO_HIGH_RELIABILITY LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_4, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_5_LEFT_LOW_LATENCY        LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_5, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_5_RIGHT_LOW_LATENCY       LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_5, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_5_STEREO_LOW_LATENCY      LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_5, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_5_LEFT_BALANCED           LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_5, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_5_RIGHT_BALANCED          LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_5, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_5_STEREO_BALANCED         LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_5, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_5_LEFT_HIGH_RELIABILITY   LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_5, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_5_RIGHT_HIGH_RELIABILITY  LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_5, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_5_STEREO_HIGH_RELIABILITY LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_5, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_6_LEFT_LOW_LATENCY        LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_6, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_6_RIGHT_LOW_LATENCY       LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_6, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_6_STEREO_LOW_LATENCY      LEA_ASE_CODEC_CONFIG_LOW_LATENCY(LC3_48_6, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_6_LEFT_BALANCED           LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_6, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_6_RIGHT_BALANCED          LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_6, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_6_STEREO_BALANCED         LEA_ASE_CODEC_CONFIG_BALANCED(LC3_48_6, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_6_LEFT_HIGH_RELIABILITY   LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_6, LEA_LOCATION_FRONT_LEFT)
#define LEA_CAPUC_LC3_48_6_RIGHT_HIGH_RELIABILITY  LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_6, LEA_LOCATION_FRONT_RIGHT)
#define LEA_CAPUC_LC3_48_6_STEREO_HIGH_RELIABILITY LEA_ASE_CODEC_CONFIG_HIGH_RELIABILITY(LC3_48_6, LEA_LOCATION_FRONT_LEFT | LEA_LOCATION_FRONT_RIGHT)

enum capuc_error_code
{
    BLE_CAPUC_ERR_START = 0x80,
    BLE_CAPUC_ERR_STOP_INVALID_VIRTUAL_HANDLE,
    BLE_CAPUC_ERR_STOP_NO_STREAMING,
    BLE_CAPUC_ERR_STOP_DEVICE_BUSY,
    BLE_CAPUC_ERR_STOP_INVALID_CONN_HANDLE,
};

enum
{
    CAP_UC_STATE_DISCONNECTED,
    CAP_UC_STATE_CONNECTED,
};

typedef void (*cap_uc_state_cb_t)(uint8_t device_id, uint8_t conn_state);
typedef void (*cap_uc_state_change_callback_func_t)(int state, const void *param);
/**
 * @brief       Starts CAP unicast music streaming on a connection.
 * @param[in]   cap_conn_handle - CAP connection handle.
 * @param[in]   p_music_config  - pointer to the desired music codec configuration.
 * @return      BLE_PRF_SUCCESS if streaming starts, otherwise an error code.
 */
int ble_capuc_start_music_streaming(uint16_t cap_conn_handle, const struct ble_ase_codec_config *p_music_config);

/**
 * @brief       Starts CAP unicast voice streaming on a connection.
 * @param[in]   cap_conn_handle - CAP connection handle.
 * @param[in]   p_music_config  - pointer to the music codec configuration.
 * @param[in]   p_voice_config  - pointer to the voice codec configuration.
 * @return      BLE_PRF_SUCCESS if streaming starts, otherwise an error code.
 */
int ble_capuc_start_voice_streaming(uint16_t cap_conn_handle, const struct ble_ase_codec_config *p_music_config, const struct ble_ase_codec_config *p_voice_config);

/**
 * @brief       Stops CAP unicast music streaming on a connection.
 * @param[in]   cap_conn_handle - CAP connection handle.
 * @return      BLE_PRF_SUCCESS if the stop command succeeds, otherwise an error code.
 */
int ble_capuc_stop_music_streaming(uint16_t cap_conn_handle);

/**
 * @brief       Stops all CAP unicast streaming on a connection.
 * @param[in]   cap_conn_handle - CAP connection handle.
 * @return      BLE_PRF_SUCCESS if streaming stops, otherwise an error code.
 */
int ble_capuc_stop_streaming(uint16_t cap_conn_handle);

/**
 * @brief       Notifies the CAP UC module of a new device connection.
 * @param[in]   conn_handle - ACL connection handle.
 * @return      none.
 * @note        Should be called when a device transitions to connected state.
 */
void cap_uc_device_connect(uint16_t conn_handle);

/**
 * @brief       Registers a callback for CAP UC state change notifications.
 * @param[in]   callback    - function invoked on state changes.
 * @return      none.
 */
void cap_uc_register_state_change_callback(cap_uc_state_change_callback_func_t callback);

/**
 * @brief       Initializes the CAP UC module with a connection state callback.
 * @param[in]   cb  - callback invoked when device connection state changes.
 * @return      none.
 */
void ble_capuc_init(cap_uc_state_cb_t cb);