/********************************************************************************************************
 * @file    ble_crypto.h
 *
 * @brief   This is the header file for TLSR/TL
 *
 * @author  Bluetooth Group
 * @date    2024
 *
 * @par     Copyright (c) 2024, Telink Semiconductor (Shanghai) Co., Ltd.
 *          All rights reserved.
 *
 *          The information contained herein is confidential property of Telink
 *          Semiconductor (Shanghai) Co., Ltd. and is available under the terms
 *          of Commercial License Agreement between Telink Semiconductor (Shanghai)
 *          Co., Ltd. and the licensee or the terms described here-in. This heading
 *          MUST NOT be removed from this file.
 *
 *          Licensee shall not delete, modify or alter (or permit any third party to delete, modify, or
 *          alter) any information contained herein in whole or in part except as expressly authorized
 *          by Telink semiconductor (shanghai) Co., Ltd. Otherwise, licensee shall be solely responsible
 *          for any claim to the extent arising out of or relating to such deletion(s), modification(s)
 *          or alteration(s).
 *
 *          Licensees are granted free, non-transferable use of the information in this
 *          file under Mutual Non-Disclosure Agreement. NO WARRANTY of ANY KIND is provided.
 *
 *******************************************************************************************************/
/** < @brief The structural definition of AES-CBC context. */
struct ble_host_aes_cbc_ctx
{
    uint8_t key[16]; /** < Key used for encryption. */

    union
    {
        uint8_t iv[16]; /** < IV used for encryption. */
        uint8_t ciphertext[16];
    };
};

/** < @brief The structural definition of AES-CMAC context. */
struct ble_host_aes_cmac_ctx
{
    uint16_t                    block_len; /** < Length of the current block. */
    uint8_t                     block[16]; /** < Current block being processed. */
    struct ble_host_aes_cbc_ctx aes_cbc;   /** < AES-CBC context used for encryption. */
    uint8_t                     mac[16];   /** < MAC generated by the context. */
};

/**
 *   @brief Swap a block of data.
 *
 *   @param[out] dst   Pointer to the destination buffer where the swapped data will be stored.
 *   @param[in]  src   Pointer to the source buffer containing the data to be swapped.
 *
 *   @note The destination and source buffers must be 128-bit long.
 */
void ble_host_crypto_swap_block(uint8_t dst[16], const uint8_t src[16]);

/**
 *   @brief Xor a block of data.
 *
 *   @param[out] dst   Pointer to the destination buffer where the result of the xor operation will be stored.
 *   @param[in]  a     Pointer to the first operand of the xor operation.
 *   @param[in]  b     Pointer to the second operand of the xor operation.
 *
 *   @note The destination and source buffers must be 128-bit long.
 */
void ble_host_crypto_xor_block(uint8_t dst[16], const uint8_t a[16], const uint8_t b[16]);

/**
 *   @brief Encrypt a block of little-endian data using AES-ECB encryption with a 128-bit key.
 *
 *   @param[in]  plaintext   Pointer to the plaintext data to be encrypted.
 *   @param[in]  key        Pointer to the 128-bit key to be used for encryption.
 *   @param[out] ciphertext Pointer to the buffer where the encrypted data will be stored.
 *
 *   @note The plaintext and ciphertext buffers must be 128-bit long and in little-endian format.
 */
void ble_host_aes_ecb_encrypt_le(const uint8_t plaintext[16], const uint8_t key[16], uint8_t ciphertext[16]);

/**
 *   @brief Encrypt a block of big-endian data using AES-ECB encryption with a 128-bit key.
 *
 *   @param[in]  plaintext   Pointer to the plaintext data to be encrypted.
 *   @param[in]  key        Pointer to the 128-bit key to be used for encryption.
 *   @param[out] ciphertext Pointer to the buffer where the encrypted data will be stored.
 *
 *   @note The plaintext and ciphertext buffers must be 128-bit long and in big-endian format.
 */
void ble_host_aes_ecb_encrypt_be(const uint8_t plaintext[16], const uint8_t key[16], uint8_t ciphertext[16]);

/**
 *   @brief Initialize the AES-CBC context with a 128-bit key and an IV.
 *
 *   @param[in]  ctx   Pointer to the AES-CBC context to be initialized.
 *   @param[in]  key   Pointer to the 128-bit key to be used for encryption.
 *   @param[in]  iv    Pointer to the 128-bit IV to be used for encryption.
 *
 *   @note The key and IV buffers must be 128-bit long and in big-endian format.
 */
void ble_host_aes_cbc_encrypt_init(struct ble_host_aes_cbc_ctx *ctx, const uint8_t key[16], const uint8_t iv[16]);

/**
 *   @brief Encrypt a block of data using AES-CBC encryption.
 *
 *   @param[in]  ctx        Pointer to the AES-CBC context to be used for encryption.
 *   @param[in]  plaintext  Pointer to the plaintext data to be encrypted.
 *
 *   @note The plaintext and ciphertext buffers must be 128-bit long and in big-endian format.
 */
void ble_host_aes_cbc_encrypt_be(struct ble_host_aes_cbc_ctx *ctx, const uint8_t plaintext[16]);

/**
 *   @brief Encrypt a block of data using AES-CBC encryption.
 *
 *   @param[in]  ctx        Pointer to the AES-CBC context to be used for encryption.
 *   @param[in]  plaintext  Pointer to the plaintext data to be encrypted.
 *
 *   @note The plaintext and ciphertext buffers must be 128-bit long and in little-endian format.
 */
void ble_host_aes_cbc_encrypt_le(struct ble_host_aes_cbc_ctx *ctx, const uint8_t plaintext[16]);

/**
 AES-CMAC test code:
    struct ble_host_aes_cmac_ctx ctx;
    char key[] = "0123456789ABCDEF";
    ble_host_aes_cmac_init(&ctx, (uint8_t*)key);
    char data[] = "1234567890123456789";
    ble_host_aes_cmac_update(&ctx, (uint8_t*)data, 19);
    ble_host_aes_cmac_update(&ctx, (uint8_t*)data, 19);
    ble_host_aes_cmac_finish(&ctx);

    printf("CMAC is %s\n", hex_to_str(ctx.mac, 16));

Output:
CMAC is 39 5a 40 7a 38 b0 68 22 a4 cf 07 80 70 99 7b 4a
 */

/**
 *   @brief Initialize the AES-CMAC context with a 128-bit key.
 *
 *   @param[in]  ctx   Pointer to the AES-CMAC context to be initialized.
 *   @param[in]  key   Pointer to the 128-bit key to be used for encryption.
 *
 *   @note The key buffer must be 128-bit long.
 */
void ble_host_aes_cmac_init(struct ble_host_aes_cmac_ctx *ctx, const uint8_t key[16]);

/**
 *   @brief Update the AES-CMAC context with a block of data.
 *
 *   @param[in]  ctx   Pointer to the AES-CMAC context to be updated.
 *   @param[in]  data  Pointer to the block of data to be added to the context.
 *   @param[in]  len   Length of the block of data to be added to the context.
 *
 *   @note must called later initial function.
 */
void ble_host_aes_cmac_update(struct ble_host_aes_cmac_ctx *ctx, const uint8_t *data, uint16_t len);

/**
 *   @brief Finalize the AES-CMAC context and generate the MAC.
 *
 *   @param[in]  ctx   Pointer to the AES-CMAC context to be finalized.
 *
 *   @note The MAC is stored in the ctx->mac.
 */
void ble_host_aes_cmac_finish(struct ble_host_aes_cmac_ctx *ctx);

/**
 *   @brief BLE Host P-256 read public key callback function type.
 *
 *   @param[in]  arg   User-defined argument passed to the callback function.
 *   @param[in]  result   true: operation successful, false: operation failure.
 *   @param[in]  private_key   Pointer to the private key.
 *   @param[in]  public_key   Pointer to the public key.
 */
typedef void (*ble_host_p256_read_key_callback)(void *arg, bool result, const uint8_t private_key[32], const uint8_t public_key[64]);

/**
 *   @brief BLE Host P-256 generate Diffie-Hellman key callback function type.
 *
 *   @param[in]  arg   User-defined argument passed to the callback function.
 *   @param[in]  result   true: operation successful, false: operation failure.
 *   @param[in]  dhkey   Pointer to the Diffie-Hellman key.
 */
typedef void (*ble_host_p256_generate_dhkey_callback)(void *arg, bool result, const uint8_t dhkey[32]);

/**
 *   @brief BLE Host P-256 read public key.
 *
 *   @param[in]  callback   Pointer to the callback function to be called when the operation is complete.
 *   @param[in]  arg   User-defined argument passed to the callback function.
 *
 *   @return   0 if the operation is started successfully.
 *             - BLE_HOST_ERR_NULL_POINTER if any of the input parameters is NULL.
 *             - BLE_HOST_ERR_INSUFFICIENT_RESOURCES if there are insufficient resources to start the operation, host malloc failed.
 */
int ble_host_p256_read_public_key(ble_host_p256_read_key_callback callback, void *arg);
// user can not call this function, it is called by ble_host_p256_read_public_key
void ble_host_p256_read_local_public_key_complete(bool result, const uint8_t private_key[32], const uint8_t public_key[64]);

/**
 *   @brief BLE Host P-256 generate Diffie-Hellman key.
 *
 *   @param[in]  callback   Pointer to the callback function to be called when the operation is complete.
 *   @param[in]  arg   User-defined argument passed to the callback function.
 *   @param[in]  local_private_key   Pointer to the local private key.
 *   @param[in]  remote_public_key   Pointer to the remote public key.
 *
 *   @return   0 if the operation is started successfully.
 *             - BLE_HOST_ERR_NULL_POINTER if any of the input parameters is NULL.
 *             - BLE_HOST_ERR_INSUFFICIENT_RESOURCES if there are insufficient resources to start the operation, host malloc failed.
 */
int ble_host_p256_generate_dhkey(ble_host_p256_generate_dhkey_callback callback, void *arg, const uint8_t local_private_key[32], const uint8_t remote_public_key[64]);
// user can not call this function, it is called by ble_host_p256_generate_dhkey
void ble_host_p256_generate_local_dhkey_complete(bool result, const uint8_t dhkey[32]);
